USE brunchindetroit;

SET @downtown_id = (SELECT id FROM neighborhoods WHERE slug = 'downtown' LIMIT 1);
SET @midtown_id = (SELECT id FROM neighborhoods WHERE slug = 'midtown' LIMIT 1);
SET @corktown_id = (SELECT id FROM neighborhoods WHERE slug = 'corktown' LIMIT 1);

INSERT INTO venues (
    slug,
    name,
    description,
    address_line1,
    city,
    state,
    zip,
    phone,
    website_url,
    instagram_url,
    neighborhood_id,
    price_range,
    brunch_hours_note,
    main_image_path,
    is_published,
    is_featured,
    featured_sort,
    published_at,
    created_at,
    updated_at
)
VALUES
(
    'sweet-maple-cafe',
    'Sweet Maple Cafe',
    'Detroit-style soul food brunch with chicken and waffles, pancakes, and weekend brunch favorites.',
    '123 Woodward Ave',
    'Detroit',
    'MI',
    '48226',
    '(313) 555-0101',
    'https://example.com',
    'https://instagram.com',
    @downtown_id,
    '$$',
    'Saturday and Sunday, 10 AM – 3 PM',
    NULL,
    1,
    1,
    1,
    NOW(),
    NOW(),
    NOW()
),
(
    'garden-rooftop',
    'The Garden Rooftop',
    'A rooftop brunch spot with city views, cocktails, vegan options, and a relaxed weekend vibe.',
    '456 Brush St',
    'Detroit',
    'MI',
    '48201',
    '(313) 555-0102',
    'https://example.com',
    'https://instagram.com',
    @midtown_id,
    '$$$',
    'Sunday, 11 AM – 4 PM',
    NULL,
    1,
    1,
    2,
    NOW(),
    NOW(),
    NOW()
),
(
    'corktown-biscuit-bar',
    'Corktown Biscuit Bar',
    'Casual brunch with biscuit sandwiches, breakfast plates, coffee, and rotating seasonal specials.',
    '789 Michigan Ave',
    'Detroit',
    'MI',
    '48216',
    '(313) 555-0103',
    'https://example.com',
    'https://instagram.com',
    @corktown_id,
    '$$',
    'Friday through Sunday, 9 AM – 2 PM',
    NULL,
    1,
    0,
    10,
    NOW(),
    NOW(),
    NOW()
)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    description = VALUES(description),
    address_line1 = VALUES(address_line1),
    city = VALUES(city),
    state = VALUES(state),
    zip = VALUES(zip),
    phone = VALUES(phone),
    website_url = VALUES(website_url),
    instagram_url = VALUES(instagram_url),
    neighborhood_id = VALUES(neighborhood_id),
    price_range = VALUES(price_range),
    brunch_hours_note = VALUES(brunch_hours_note),
    main_image_path = VALUES(main_image_path),
    is_published = VALUES(is_published),
    is_featured = VALUES(is_featured),
    featured_sort = VALUES(featured_sort),
    updated_at = NOW();